spring:
  application:
    name: library-service

  mvc:
    log-request-details: true

  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:190817}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        highlight_sql: false
        use_sql_comments: false
        generate_statistics: false

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

logging:
  level:
    com.library: DEBUG
    org.springframework.web: INFO
    org.springframework.web.servlet.DispatcherServlet: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: OFF
    org.hibernate.stat: OFF

server:
  port: 8080
